### ISSUE TITLE
add support for firebird 3 / python 3 driver 

### ISSUE THREAD

**Issue by mariuz** [pauldex/sqlalchemy-firebird#29]
The firebird-driver package provides driver for Python 3.8+ and Firebird 3+. This driver uses new Firebird OO API provided by fbclient library. You can download it or install directly from Python Package Index.

https://pypi.org/project/firebird-driver/
https://firebird-driver.readthedocs.io/en/latest/

via 

https://firebirdsql.org/en/python-driver/

**Comment by fdcastel** [comment]
Any plans to migrate to this package?

**Comment by pauldex** [comment]
Yes, we will add support for the firebird-driver package in addition to fdb.  The connectivity page for Firebird with python ([https://firebirdsql.org/en/python-driver/]), indicates that **fdb** is the legacy driver and **firebird-driver** is the package to use going forward.

**Comment by pauldex** [comment]
That would be awesome, I can definitely use your assistance with this.  I have some ideas, but not a lot of experience with this level of Python.

 

Paul

**Comment by hmoffatt** [comment]
Please support the old (current) API as well, else you lose support for Firebird 2.5.

**Comment by fdcastel** [comment]
I've started a new dialect for SQLAlchemy 2.0 using [firebird-driver](https://pypi.org/project/firebird-driver/). 

I expect to submit a PR in ~10 days.

**Comment by fdcastel** [comment]
Given that both KInterbasDB and Firebird 1.5 are long dead now, I intend to remove KInterbasDB support for the next version.

This will keep only `fdb` (using [FDB](https://pypi.python.org/pypi/fdb/) package) and `fdb3` (using [firebird-driver](https://pypi.python.org/pypi/firebird-driver/) package) dialects in this project.

@pauldex @pcisar @mariuz opinions?

**Comment by mariuz** [comment]
@fdcastel makes sense , please do the KInterbasDB cleanup :)

**Comment by fdcastel** [comment]
BTW: What should we name the new dialect? 

I'm using `fdb3` for now but it may cause some confusion with `fdb` driver.

`driver` could be an option. The url would be `firebird+driver://`. but I'm still unsure...

Also, the idea would be to change the default `firebird://` url to the new dialect when all tests pass.

**Comment by fdcastel** [comment]
I pushed my current work [in this repository](https://github.com/fdcastel/sqlalchemy-firebird/tree/v2).

36 tests failing, yet. Tested with 5 combinations:

- `firebird-driver` with Firebird 4.0
- `firebird-driver` with Firebird 3.0
- `fdb` with Firebird 4.0
- `fdb` with Firebird 3.0
- `fdb` with Firebird 2.5

Soon...

**Comment by pauldex** [comment]
I was planning on naming it firebird.  The url would be firebird+firebird://.

 

My reasoning is that the name used as the base in the fdb dbapi (reference here <https://fdb.readthedocs.io/en/v2.0/genindex.html> ) is fdb and the name used as the base for the firebird driver dbapi (reference here <https://firebird-base.readthedocs.io/en/latest/genindex.html> ) is firebird.  Using the name of the dbapi for the dialect name makes it easy to look things up and to document references.

 

Agree, we’ll update the default setting for the dialect when enough tests are passing.  Since Python 3.8+ and Firebird 3+ are required for firebird-driver, that could be the default choice when those conditions are met.  All other conditions would use the fallback of fdb.  Either could be chosen as a default as well.

**Comment by pauldex** [comment]
This is with SQLAlchemy 2.0, correct?  We’ll need to test it with 1.4 as well.

**Comment by fdcastel** [comment]
> This is with SQLAlchemy 2.0, correct? We’ll need to test it with 1.4 as well.

Agreed. I will revert my changes to require SQLAlchemy 1.4+.

**Comment by fdcastel** [comment]
Done in #48.

**Comment by pauldex** [comment]
I'm closing this issue due to the release of sqlalchemy-firebird 2.0
